#
#    Copyright 2018 NewClarity Consulting, LLC
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

version: 2

jobs:
    build:
        docker:
            - image: circleci/php:7.1.21-cli-node-browsers

        working_directory: ~/source

        environment:
            CI_SOURCED_FILE: /home/circleci/source/.circleci/wp-devops/sourced.sh

        steps:
            - checkout

            - store_artifacts:
                  path: ./project.json
                  destination: project.json

            - store_artifacts:
                  path: ./composer.json
                  destination: composer.json

            - run:
                  name: Bootstrapping WP DevOps
                  command: |
                      wp_devops="$(cat project.json|jq -r '.deploy.frameworks.wp_devops')"
                      ref_type=$(echo "${wp_devops}"|jq -r '.ref_type')
                      cd .circleci
                      rm -rf wp-devops
                      git clone git@github.com:wplib/wp-devops.git
                      cd wp-devops
                      if [ 'branch' == "${ref_type}" ] ; then
                          branch=$(echo "${wp_devops}"|jq -r '.branch')
                          if [ "master" != "${branch}" ]; then
                            git checkout -b "${branch}" "origin/${branch}"
                          fi
                      else
                          tag=$(echo "${wp_devops}"|jq -r '.tag')
                          git checkout "${tag}"
                      fi

            - store_artifacts:
                  path: .circleci/wp-devops
                  destination: wp-devops

            - run: .circleci/wp-devops/deploy.sh

            - store_artifacts:
                  path: /tmp/log.txt
                  destination: deploy.log

            - run:
                  name: Generate Error Report
                  when: on_fail
                  command: cat /tmp/log.txt

